name: CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: 'jsalazarsdevco/flutter-test' 
  AWS_REGION: 'us-east-1'
  ECR_REPOSITORY: 'tmp-jdss-flutter_web_app'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable
    - name: Build flutter web
      run: flutter build web --release
      
  docker-build:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Tag Docker image for ECR
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.AWS_ACCESS_KEY_ID_POC }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
      - name: Push Docker image to Amazon ECR
        run: docker push ${{ secrets.AWS_ACCESS_KEY_ID_POC }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
